# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Chris\Desktop\CICLO VIII\DSI\Windows\GPromotorasWindow.ui'
#
# Created: Sat Aug 24 17:20:23 2013
#      by: pyside-uic 0.2.14 running on PySide 1.2.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_gPromotorasWindow(object):
    def setupUi(self, gPromotorasWindow):
        gPromotorasWindow.setObjectName("gPromotorasWindow")
        gPromotorasWindow.resize(552, 390)
        gPromotorasWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtGui.QWidget(gPromotorasWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setContentsMargins(10, 15, 10, 10)
        self.formLayout.setSpacing(10)
        self.formLayout.setObjectName("formLayout")
        self.nombreLbl = QtGui.QLabel(self.centralwidget)
        self.nombreLbl.setObjectName("nombreLbl")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.nombreLbl)
        self.nombreTxt = QtGui.QLineEdit(self.centralwidget)
        self.nombreTxt.setObjectName("nombreTxt")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.nombreTxt)
        self.codigoLbl = QtGui.QLabel(self.centralwidget)
        self.codigoLbl.setObjectName("codigoLbl")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.codigoLbl)
        self.codigoTxt = QtGui.QLineEdit(self.centralwidget)
        self.codigoTxt.setObjectName("codigoTxt")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.codigoTxt)
        self.telefonoLbl = QtGui.QLabel(self.centralwidget)
        self.telefonoLbl.setObjectName("telefonoLbl")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.telefonoLbl)
        self.telefonoTxt = QtGui.QLineEdit(self.centralwidget)
        self.telefonoTxt.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.telefonoTxt.setObjectName("telefonoTxt")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.telefonoTxt)
        self.departamentoLbl = QtGui.QLabel(self.centralwidget)
        self.departamentoLbl.setObjectName("departamentoLbl")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.departamentoLbl)
        self.deptoCbx = QtGui.QComboBox(self.centralwidget)
        self.deptoCbx.setObjectName("deptoCbx")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.deptoCbx)
        self.direccionLbl = QtGui.QLabel(self.centralwidget)
        self.direccionLbl.setObjectName("direccionLbl")
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.direccionLbl)
        self.direccionTxt = QtGui.QTextEdit(self.centralwidget)
        self.direccionTxt.setObjectName("direccionTxt")
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.direccionTxt)
        self.horizontalLayout.addLayout(self.formLayout)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_2.addWidget(self.line)
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setAutoFillBackground(False)
        self.groupBox.setTitle("")
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setFlat(True)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setSpacing(10)
        self.verticalLayout_2.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayoutBotones = QtGui.QVBoxLayout()
        self.verticalLayoutBotones.setSpacing(3)
        self.verticalLayoutBotones.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayoutBotones.setObjectName("verticalLayoutBotones")
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayoutBotones.addItem(spacerItem)
        self.buscarBtn = QtGui.QPushButton(self.groupBox)
        self.buscarBtn.setAutoFillBackground(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("lupa.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buscarBtn.setIcon(icon)
        self.buscarBtn.setObjectName("buscarBtn")
        self.verticalLayoutBotones.addWidget(self.buscarBtn)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayoutBotones.addItem(spacerItem1)
        self.agregarBtn = QtGui.QPushButton(self.groupBox)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("addbd2.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.agregarBtn.setIcon(icon1)
        self.agregarBtn.setIconSize(QtCore.QSize(16, 16))
        self.agregarBtn.setObjectName("agregarBtn")
        self.verticalLayoutBotones.addWidget(self.agregarBtn)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayoutBotones.addItem(spacerItem2)
        self.modificarBtn = QtGui.QPushButton(self.groupBox)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("lapiz.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.modificarBtn.setIcon(icon2)
        self.modificarBtn.setObjectName("modificarBtn")
        self.verticalLayoutBotones.addWidget(self.modificarBtn)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayoutBotones.addItem(spacerItem3)
        self.eliminarBtn = QtGui.QPushButton(self.groupBox)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("trash3.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.eliminarBtn.setIcon(icon3)
        self.eliminarBtn.setObjectName("eliminarBtn")
        self.verticalLayoutBotones.addWidget(self.eliminarBtn)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayoutBotones.addItem(spacerItem4)
        self.guardarBtn = QtGui.QPushButton(self.groupBox)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("save2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.guardarBtn.setIcon(icon4)
        self.guardarBtn.setObjectName("guardarBtn")
        self.verticalLayoutBotones.addWidget(self.guardarBtn)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayoutBotones.addItem(spacerItem5)
        self.cancelarBtn = QtGui.QPushButton(self.groupBox)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("cancel.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cancelarBtn.setIcon(icon5)
        self.cancelarBtn.setObjectName("cancelarBtn")
        self.verticalLayoutBotones.addWidget(self.cancelarBtn)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayoutBotones.addItem(spacerItem6)
        self.verticalLayout_2.addLayout(self.verticalLayoutBotones)
        self.horizontalLayout_2.addWidget(self.groupBox)
        gPromotorasWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(gPromotorasWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 552, 21))
        self.menubar.setStyleSheet("background-color: rgb(231, 231, 231);\n"
"selection-background-color: rgb(255, 170, 0);\n"
"selection-color: rgb(0, 0, 255);")
        self.menubar.setObjectName("menubar")
        self.menu_Actualizacion = QtGui.QMenu(self.menubar)
        self.menu_Actualizacion.setObjectName("menu_Actualizacion")
        self.menu_PAF = QtGui.QMenu(self.menu_Actualizacion)
        self.menu_PAF.setObjectName("menu_PAF")
        self.menu_Consultas_y_Reportes = QtGui.QMenu(self.menubar)
        self.menu_Consultas_y_Reportes.setObjectName("menu_Consultas_y_Reportes")
        self.menuAfiliados_ingresados_en_el_mes = QtGui.QMenu(self.menu_Consultas_y_Reportes)
        self.menuAfiliados_ingresados_en_el_mes.setObjectName("menuAfiliados_ingresados_en_el_mes")
        self.menu_Especiales = QtGui.QMenu(self.menubar)
        self.menu_Especiales.setObjectName("menu_Especiales")
        self.menu_Correcciones = QtGui.QMenu(self.menubar)
        self.menu_Correcciones.setObjectName("menu_Correcciones")
        gPromotorasWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(gPromotorasWindow)
        self.statusbar.setStyleSheet("background-color: rgb(216, 216, 216);")
        self.statusbar.setObjectName("statusbar")
        self.widget = QtGui.QWidget(self.statusbar)
        self.widget.setGeometry(QtCore.QRect(0, 0, 451, 30))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setAutoFillBackground(False)
        self.widget.setObjectName("widget")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout_3.setContentsMargins(5, 0, 10, 10)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.toolButton = QtGui.QToolButton(self.widget)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("images.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton.setIcon(icon6)
        self.toolButton.setAutoRaise(True)
        self.toolButton.setObjectName("toolButton")
        self.horizontalLayout_3.addWidget(self.toolButton)
        self.label = QtGui.QLabel(self.widget)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.usuarioLbl = QtGui.QLabel(self.widget)
        self.usuarioLbl.setObjectName("usuarioLbl")
        self.horizontalLayout_3.addWidget(self.usuarioLbl)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem7)
        self.toolButton_2 = QtGui.QToolButton(self.widget)
        self.toolButton_2.setAutoFillBackground(False)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("descarga.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_2.setIcon(icon7)
        self.toolButton_2.setAutoRaise(True)
        self.toolButton_2.setObjectName("toolButton_2")
        self.horizontalLayout_3.addWidget(self.toolButton_2)
        self.label_3 = QtGui.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.fechaLbl = QtGui.QLabel(self.widget)
        self.fechaLbl.setObjectName("fechaLbl")
        self.horizontalLayout_3.addWidget(self.fechaLbl)
        gPromotorasWindow.setStatusBar(self.statusbar)
        self.action_Maestro_de_Afiliados = QtGui.QAction(gPromotorasWindow)
        self.action_Maestro_de_Afiliados.setObjectName("action_Maestro_de_Afiliados")
        self.action_Pagadur_as = QtGui.QAction(gPromotorasWindow)
        self.action_Pagadur_as.setObjectName("action_Pagadur_as")
        self.action_Departamentos_y_Municipios = QtGui.QAction(gPromotorasWindow)
        self.action_Departamentos_y_Municipios.setObjectName("action_Departamentos_y_Municipios")
        self.action_Promotoras = QtGui.QAction(gPromotorasWindow)
        self.action_Promotoras.setObjectName("action_Promotoras")
        self.action_PAF_I = QtGui.QAction(gPromotorasWindow)
        self.action_PAF_I.setObjectName("action_PAF_I")
        self.actionPAF_II = QtGui.QAction(gPromotorasWindow)
        self.actionPAF_II.setObjectName("actionPAF_II")
        self.actionGestion_Beneficiarios = QtGui.QAction(gPromotorasWindow)
        self.actionGestion_Beneficiarios.setObjectName("actionGestion_Beneficiarios")
        self.action_Afiliados_Ingresados_mes_alfab_tico = QtGui.QAction(gPromotorasWindow)
        self.action_Afiliados_Ingresados_mes_alfab_tico.setObjectName("action_Afiliados_Ingresados_mes_alfab_tico")
        self.actionPor_promotoras = QtGui.QAction(gPromotorasWindow)
        self.actionPor_promotoras.setObjectName("actionPor_promotoras")
        self.action_En_orden_alfab_tico = QtGui.QAction(gPromotorasWindow)
        self.action_En_orden_alfab_tico.setObjectName("action_En_orden_alfab_tico")
        self.action_Descuentos_para_nuevos_afiliados = QtGui.QAction(gPromotorasWindow)
        self.action_Descuentos_para_nuevos_afiliados.setObjectName("action_Descuentos_para_nuevos_afiliados")
        self.actionDesc_nuevos_afiliados_Validaci_n = QtGui.QAction(gPromotorasWindow)
        self.actionDesc_nuevos_afiliados_Validaci_n.setObjectName("actionDesc_nuevos_afiliados_Validaci_n")
        self.actionPAF_III = QtGui.QAction(gPromotorasWindow)
        self.actionPAF_III.setObjectName("actionPAF_III")
        self.actionPAF_III_2 = QtGui.QAction(gPromotorasWindow)
        self.actionPAF_III_2.setObjectName("actionPAF_III_2")
        self.actionAfiliados_por_orden_alfab_ticos = QtGui.QAction(gPromotorasWindow)
        self.actionAfiliados_por_orden_alfab_ticos.setObjectName("actionAfiliados_por_orden_alfab_ticos")
        self.actionAfiliados_por_pagadur_as = QtGui.QAction(gPromotorasWindow)
        self.actionAfiliados_por_pagadur_as.setObjectName("actionAfiliados_por_pagadur_as")
        self.actionTotales_por_pagadur_as = QtGui.QAction(gPromotorasWindow)
        self.actionTotales_por_pagadur_as.setObjectName("actionTotales_por_pagadur_as")
        self.actionNombres_repetidos = QtGui.QAction(gPromotorasWindow)
        self.actionNombres_repetidos.setObjectName("actionNombres_repetidos")
        self.actionMaestro_Pagadur_as = QtGui.QAction(gPromotorasWindow)
        self.actionMaestro_Pagadur_as.setObjectName("actionMaestro_Pagadur_as")
        self.actionMaestro_departamentos_y_municipios = QtGui.QAction(gPromotorasWindow)
        self.actionMaestro_departamentos_y_municipios.setObjectName("actionMaestro_departamentos_y_municipios")
        self.actionMaestro_PAF = QtGui.QAction(gPromotorasWindow)
        self.actionMaestro_PAF.setObjectName("actionMaestro_PAF")
        self.actionMaestro_promotoras = QtGui.QAction(gPromotorasWindow)
        self.actionMaestro_promotoras.setObjectName("actionMaestro_promotoras")
        self.actionReindexar_archivos = QtGui.QAction(gPromotorasWindow)
        self.actionReindexar_archivos.setObjectName("actionReindexar_archivos")
        self.actionPar_metros = QtGui.QAction(gPromotorasWindow)
        self.actionPar_metros.setObjectName("actionPar_metros")
        self.actionCorrecciones_al_maestro = QtGui.QAction(gPromotorasWindow)
        self.actionCorrecciones_al_maestro.setObjectName("actionCorrecciones_al_maestro")
        self.actionReporte_de_correcciones = QtGui.QAction(gPromotorasWindow)
        self.actionReporte_de_correcciones.setObjectName("actionReporte_de_correcciones")
        self.menu_PAF.addAction(self.action_PAF_I)
        self.menu_PAF.addAction(self.actionPAF_II)
        self.menu_PAF.addAction(self.actionPAF_III_2)
        self.menu_Actualizacion.addAction(self.action_Maestro_de_Afiliados)
        self.menu_Actualizacion.addSeparator()
        self.menu_Actualizacion.addAction(self.action_Pagadur_as)
        self.menu_Actualizacion.addAction(self.action_Departamentos_y_Municipios)
        self.menu_Actualizacion.addAction(self.action_Promotoras)
        self.menu_Actualizacion.addAction(self.menu_PAF.menuAction())
        self.menu_Actualizacion.addAction(self.actionGestion_Beneficiarios)
        self.menuAfiliados_ingresados_en_el_mes.addAction(self.actionPor_promotoras)
        self.menuAfiliados_ingresados_en_el_mes.addAction(self.action_En_orden_alfab_tico)
        self.menuAfiliados_ingresados_en_el_mes.addAction(self.actionPAF_III)
        self.menu_Consultas_y_Reportes.addAction(self.menuAfiliados_ingresados_en_el_mes.menuAction())
        self.menu_Consultas_y_Reportes.addAction(self.action_Afiliados_Ingresados_mes_alfab_tico)
        self.menu_Consultas_y_Reportes.addAction(self.action_Descuentos_para_nuevos_afiliados)
        self.menu_Consultas_y_Reportes.addAction(self.actionDesc_nuevos_afiliados_Validaci_n)
        self.menu_Consultas_y_Reportes.addSeparator()
        self.menu_Consultas_y_Reportes.addAction(self.actionAfiliados_por_orden_alfab_ticos)
        self.menu_Consultas_y_Reportes.addAction(self.actionAfiliados_por_pagadur_as)
        self.menu_Consultas_y_Reportes.addAction(self.actionTotales_por_pagadur_as)
        self.menu_Consultas_y_Reportes.addAction(self.actionNombres_repetidos)
        self.menu_Consultas_y_Reportes.addSeparator()
        self.menu_Consultas_y_Reportes.addAction(self.actionMaestro_Pagadur_as)
        self.menu_Consultas_y_Reportes.addAction(self.actionMaestro_departamentos_y_municipios)
        self.menu_Consultas_y_Reportes.addAction(self.actionMaestro_PAF)
        self.menu_Consultas_y_Reportes.addAction(self.actionMaestro_promotoras)
        self.menu_Especiales.addAction(self.actionReindexar_archivos)
        self.menu_Especiales.addAction(self.actionPar_metros)
        self.menu_Correcciones.addAction(self.actionCorrecciones_al_maestro)
        self.menu_Correcciones.addAction(self.actionReporte_de_correcciones)
        self.menubar.addAction(self.menu_Actualizacion.menuAction())
        self.menubar.addAction(self.menu_Consultas_y_Reportes.menuAction())
        self.menubar.addAction(self.menu_Especiales.menuAction())
        self.menubar.addAction(self.menu_Correcciones.menuAction())

        self.retranslateUi(gPromotorasWindow)
        QtCore.QMetaObject.connectSlotsByName(gPromotorasWindow)

    def retranslateUi(self, gPromotorasWindow):
        gPromotorasWindow.setWindowTitle(QtGui.QApplication.translate("gPromotorasWindow", "MAESTRO - Gestión Promotoras", None, QtGui.QApplication.UnicodeUTF8))
        self.nombreLbl.setText(QtGui.QApplication.translate("gPromotorasWindow", "Nombre: ", None, QtGui.QApplication.UnicodeUTF8))
        self.codigoLbl.setText(QtGui.QApplication.translate("gPromotorasWindow", "Código:", None, QtGui.QApplication.UnicodeUTF8))
        self.telefonoLbl.setText(QtGui.QApplication.translate("gPromotorasWindow", "Teléfono: ", None, QtGui.QApplication.UnicodeUTF8))
        self.telefonoTxt.setInputMask(QtGui.QApplication.translate("gPromotorasWindow", " 9999 - 9999; ", None, QtGui.QApplication.UnicodeUTF8))
        self.telefonoTxt.setText(QtGui.QApplication.translate("gPromotorasWindow", "  - ", None, QtGui.QApplication.UnicodeUTF8))
        self.departamentoLbl.setText(QtGui.QApplication.translate("gPromotorasWindow", "Departamento: ", None, QtGui.QApplication.UnicodeUTF8))
        self.direccionLbl.setText(QtGui.QApplication.translate("gPromotorasWindow", "Dirección: ", None, QtGui.QApplication.UnicodeUTF8))
        self.buscarBtn.setText(QtGui.QApplication.translate("gPromotorasWindow", "Buscar", None, QtGui.QApplication.UnicodeUTF8))
        self.agregarBtn.setText(QtGui.QApplication.translate("gPromotorasWindow", "Agregar", None, QtGui.QApplication.UnicodeUTF8))
        self.modificarBtn.setText(QtGui.QApplication.translate("gPromotorasWindow", "Modificar", None, QtGui.QApplication.UnicodeUTF8))
        self.eliminarBtn.setText(QtGui.QApplication.translate("gPromotorasWindow", "Eliminar", None, QtGui.QApplication.UnicodeUTF8))
        self.guardarBtn.setText(QtGui.QApplication.translate("gPromotorasWindow", "Guardar", None, QtGui.QApplication.UnicodeUTF8))
        self.cancelarBtn.setText(QtGui.QApplication.translate("gPromotorasWindow", "Cancelar", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Actualizacion.setTitle(QtGui.QApplication.translate("gPromotorasWindow", " Actualización", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_PAF.setTitle(QtGui.QApplication.translate("gPromotorasWindow", "PAF", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Consultas_y_Reportes.setTitle(QtGui.QApplication.translate("gPromotorasWindow", " Consultas y Reportes", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAfiliados_ingresados_en_el_mes.setTitle(QtGui.QApplication.translate("gPromotorasWindow", "Afiliados ingresados en el mes", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Especiales.setTitle(QtGui.QApplication.translate("gPromotorasWindow", " Especiales", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Correcciones.setTitle(QtGui.QApplication.translate("gPromotorasWindow", " Correcciones", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton.setText(QtGui.QApplication.translate("gPromotorasWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("gPromotorasWindow", "Usuario: ", None, QtGui.QApplication.UnicodeUTF8))
        self.usuarioLbl.setText(QtGui.QApplication.translate("gPromotorasWindow", "Kath Linares", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_2.setText(QtGui.QApplication.translate("gPromotorasWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("gPromotorasWindow", "Fecha: ", None, QtGui.QApplication.UnicodeUTF8))
        self.fechaLbl.setText(QtGui.QApplication.translate("gPromotorasWindow", "24 / 08 / 2013", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Maestro_de_Afiliados.setText(QtGui.QApplication.translate("gPromotorasWindow", "Maestro de Afiliados", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Pagadur_as.setText(QtGui.QApplication.translate("gPromotorasWindow", "Pagadurías", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Departamentos_y_Municipios.setText(QtGui.QApplication.translate("gPromotorasWindow", "Departamentos y Municipios", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Promotoras.setText(QtGui.QApplication.translate("gPromotorasWindow", "Promotoras", None, QtGui.QApplication.UnicodeUTF8))
        self.action_PAF_I.setText(QtGui.QApplication.translate("gPromotorasWindow", "PAF I", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPAF_II.setText(QtGui.QApplication.translate("gPromotorasWindow", "PAF II", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGestion_Beneficiarios.setText(QtGui.QApplication.translate("gPromotorasWindow", "Gestión Beneficiarios", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Afiliados_Ingresados_mes_alfab_tico.setText(QtGui.QApplication.translate("gPromotorasWindow", "Emisión de carnés", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPor_promotoras.setText(QtGui.QApplication.translate("gPromotorasWindow", "Por promotoras", None, QtGui.QApplication.UnicodeUTF8))
        self.action_En_orden_alfab_tico.setText(QtGui.QApplication.translate("gPromotorasWindow", "En orden alfabético", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Descuentos_para_nuevos_afiliados.setText(QtGui.QApplication.translate("gPromotorasWindow", "Descuentos para nuevos afiliados", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDesc_nuevos_afiliados_Validaci_n.setText(QtGui.QApplication.translate("gPromotorasWindow", "Desc nuevos afiliados **Validación", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPAF_III.setText(QtGui.QApplication.translate("gPromotorasWindow", "PAF III", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPAF_III_2.setText(QtGui.QApplication.translate("gPromotorasWindow", "PAF III", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAfiliados_por_orden_alfab_ticos.setText(QtGui.QApplication.translate("gPromotorasWindow", "Afiliados por orden alfabético", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAfiliados_por_pagadur_as.setText(QtGui.QApplication.translate("gPromotorasWindow", "Afiliados por pagadurías", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTotales_por_pagadur_as.setText(QtGui.QApplication.translate("gPromotorasWindow", "Totales por pagadurías", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNombres_repetidos.setText(QtGui.QApplication.translate("gPromotorasWindow", "Nombres repetidos", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMaestro_Pagadur_as.setText(QtGui.QApplication.translate("gPromotorasWindow", "Maestro pagadurías", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMaestro_departamentos_y_municipios.setText(QtGui.QApplication.translate("gPromotorasWindow", "Maestro departamentos y municipios", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMaestro_PAF.setText(QtGui.QApplication.translate("gPromotorasWindow", "Maestro PAF", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMaestro_promotoras.setText(QtGui.QApplication.translate("gPromotorasWindow", "Maestro promotoras", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReindexar_archivos.setText(QtGui.QApplication.translate("gPromotorasWindow", "Reindexar archivos", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPar_metros.setText(QtGui.QApplication.translate("gPromotorasWindow", "Parámetros", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCorrecciones_al_maestro.setText(QtGui.QApplication.translate("gPromotorasWindow", "Correcciones al maestro", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReporte_de_correcciones.setText(QtGui.QApplication.translate("gPromotorasWindow", "Reporte de correcciones", None, QtGui.QApplication.UnicodeUTF8))

